<!DOCTYPE html>
<html>
<head>
	<title>Retry</title>
</head>
<body>
<script type="text/javascript">
	// Defining a custom error that inherits from inbuilt Error class
	class MultiplicatorUnitFailure extends Error {};

	function primitiveMultiply(a,b){
		// Generating a random number from 0 to 10
		let n = Math.round(Math.random(0,1)*10);
		if (n == 2 || n == 7) return a*b; // returning results for n values of 2 and 7 only
		throw new MultiplicatorUnitFailure('A Multiplicator Unit failure happened');
	}
	// Running an infinite fall loops that only breaks when a result is obtained
	for(;;) {
		try {
			let result = primitiveMultiply(5,23);
			console.log('The result of the multiplication is', result);
			break;
		} catch (error) {
			// Selectively catching the expected error and throwing the rest. 
			if (error instanceof MultiplicatorUnitFailure) console.log('The expected Multiplicator unit failure error occured');
			else throw error;
		}
	}

</script>
</body>
</html>